### PR TITLE
Move tiles for responses to a YML file

### PR DESCRIPTION
**Pull request by hackebrot**
This should also fix the line-length errors reported by flake8.

### CODE REVIEW

**Review by ashrivastava-qa — APPROVED** [review]
LGTM 👍 
The only suggestion is to squash your commits into one for better readability.

**Comment by hackebrot** [comment]
Hi @ashrivastava-qa! 👋🏻 

Thanks for the review.

Are you referring to the Git history on our `main` branch once we merge this pull request?

**Comment by ashrivastava-qa** [comment]
Yeah that too. But I was referring to the multiple commits you have created above and squashing it to one. For reference here's a doc that will guide you on how to do it: [https://github.com/mozilla-mobile/firefox-ios/wiki/Writing-a-first-XCUI-test-from-the-scratch#squashing-commits]

**Comment by hackebrot** [comment]
GitHub features this here in the pull request UI too, but I don't quite follow how this would improve readability. Let's discuss that in our next 1:1? If we come to the conclusion that we want to require squashing in this repository then we can update the settings to enforce that.

**Comment by jrconlin** [comment]
FWIW, On the dev side we don't squash commits until the final merge mostly to preserve changes. I find it easier to spot differences, particularly with lengthy commits, by just viewing individual changes rather than re-reading everything,

Github offers the project setting to disable "Merge commits" in favor of "Squash" or "Rebase commits". I tend to disable "Merge" so that the final merge is cleaner.

**Comment by hackebrot** [comment]
Thank you for your input @jrconlin! I'd be happy to use the same repo settings here as for Contile.

**Pull request merged**
